# Generated by Django 4.0 on 2021-12-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorten',
            field=models.SlugField(unique=True),
        ),
    ]
